INSERT INTO productos (id, genero_id,nombre,autor,descripcion, precio,tipo, stock, oferta, fecha, imagen,pdf)
 VALUES

        /*THRILLER*/
        (NULL, '4', 'El juego del angel','Carlos Ruiz Zafon', 'Resume', '17', 'ebook','12', NULL, '2019-04-11', 'assets/img/libros/el-juego-del-angel.jpg','assets/img/pdf/El-Juego-del-Angel.pdf'),
        (NULL, '4', 'El laberinto de los espiritus','Carlos Ruiz Zafon', 'Resume', '17', 'fisico','12', NULL, '2019-04-11', 'assets/img/libros/el-laberinto-de-los-espiritus.jpg',null),
        (NULL, '4', 'El prisioner del cielo','Carlos Ruiz Zafon', 'Resume', '17', 'ebook','12', NULL, '2019-04-11', 'assets/img/libros/el-prisionero-del-cielo.jpg',null),
        (NULL, '4', 'La sombra del viento','Carlos Ruiz Zafon', 'Resume', '17', 'fisico','12', NULL, '2019-04-11', 'assets/img/libros/la-sombra-del-viento.jpg',null),
        (NULL, '4', 'La chica del tren','Paula Hawkins', 'Resume', '17', 'ebook','12', NULL, '2019-04-11', 'assets/img/libros/la-chica-del-tren.jpg',null),
        (NULL, '4', 'Cicatriz','Juan Gomez Jurado', 'Resume', '17', 'ebook','12', NULL, '2019-04-11', 'assets/img/libros/cicatrizz.jpg',null),
        (NULL, '4', 'Reina Roja','Juan Gomez Jurado', 'Resume', '17', 'fisico','12', NULL, '2019-04-11', 'assets/img/libros/roja.jpg',null),
        (NULL, '4', 'It','Stephen King', 'Resume', '17', 'fisico','12', NULL, '2019-04-11', 'assets/img/libros/it.jpg',null),
        (NULL, '4', 'La pareja de al lado','Shari Lapeña', 'Resume', '17', 'ebook','12', NULL, '2019-04-11', 'assets/img/libros/la-pareja-de-al-lado.jpg',null),
        (NULL, '4', 'No abras los ojos','John Verdon', 'Resume', '17', 'fisico','12', NULL, '2019-04-11', 'assets/img/libros/no-abras-los-ojos.jpg',null),
        /*Juvenil*/
       (NULL, '3', 'El bestiario de Axlin','Laura Gallego', 'El mundo de Axlin está plagado de monstruos. Algunos atacan a los viajeros en los caminos, otros asedian las aldeas hasta que logran arrasarlas por completo y otros entran en las casas por las noches para llevarse a los niños mientras duermen.Axlin ha crecido siendo consciente de que cualquier día le puede tocar a ella. Su gente ha sobrevivido a los monstruos durante generaciones y ha aprendido a evitarlos en la medida de lo posible. Pero un día Axlin descubre que existen muchos tipos de monstruos diferentes, que cada aldea se enfrenta a sus propias pesadillas y que hay criaturas que no conoce y ante las que no sabe cómo defenderse.Axlin es la escriba de su aldea, la única que sabe leer y escribir. Debido a ello, nadie de su entorno comprende realmente la importancia de su trabajo. Pero ella se ha propuesto investigar todo lo que pueda sobre los monstruos y plasmar sus descubrimientos en un libro que pueda servir de guía y protección a otras personas. Por eso decide partir con los buhoneros en una larga ruta para reunir la sabiduría ancestral de las aldeas en su precaria lucha contra los monstruos. No obstante, a lo largo de su viaje descubrirá cosas que jamás habría imaginado cuando partió.', '15','fisico','12', NULL, '2019-04-11', 'assets/img/libros/gc1.jpg',null),
        (NULL, '3', 'El secreto de Xein','Laura Gallego', 'Los caminos de Axlin y Xein vuelven a cruzarse, pero ellos parecen estar más distanciados que nunca. Axlin trabaja en la biblioteca y sigue recopilando información para completar su bestiario mientras investiga una presencia inusual de monstruos dentro de los muros de la Ciudadela. Además, al intentar ayudar a su amigo Dex con un problema personal se ve envuelta en un conflicto que implica a varias familias aristocráticas de la ciudad vieja. Xein, por su parte, se ha convertido en uno más de los Guardianes que protegen a los habitantes de la Ciudadela de los monstruos que los acechan. Su lealtad a la Guardia lo obliga a mantener sus nuevos conocimientos ocultos para el resto de la gente y especialmente para Axlin, lo cual levanta otro muro entre los dos. Todo ello causará enfrentamientos entre ambos cada vez que vuelvan a encontrarse, pero también hará saltar chispas que arderán con más fuerza a causa de su pasado en común.', '17', 'ebook','12', NULL, '2019-04-11', 'assets/img/libros/gc2.jpg',null),
        (NULL, '3', 'La mision de Rox', 'Laura Gallego','En esta última entrega de la trilogía «Guardianes de la Ciudadela», los destinos de los protagonistas se entrelazan una vez más, condicionados por secretos y revelaciones que pondrán en peligro los cimientos de su relación, pero que también podrían suponer la clave para salvar su mundo de la tiranía de los monstruos.Rox ha partido a la región del oeste, devastada por los monstruos, en busca de una aldea perdida habitada por Guardianes. Mientras una riada de supervivientes acude a la Ciudadela en busca de un refugio seguro, tras sus muros florece un nuevo movimiento filosófico, la Senda del Manantial, cuyo líder predica el fin del mundo conocido... para bien o para mal.Xein, por su parte, ha sido enviado a la Última Frontera, el lugar desde donde los Guardianes defienden la civilización de la amenaza de los monstruos, y de donde pocos regresan con vida. Axlin se ha propuesto rescatarlo; mientras prepara su viaje, y al investigar sobre la Senda del Manantial con la ayuda de Dex, encuentra pistas que la conducen a una época anterior a la Ciudadela, donde podría hallarse el origen de la plaga de monstruos que asola su mundo.La verdad es una joya de múltiples facetas.', '17','fisico', '12', NULL, '2019-04-11', 'assets/img/libros/gc3.jpg',null),
        (NULL, '3', 'El secreto de Xein','Laura Gallego', 'Resume', '17', 'ebook','12', NULL, '2019-04-11', 'assets/img/libros/en-llamas.jpg',null),
        (NULL, '3', 'El secreto de Xein','Laura Gallego', 'Resume', '17', 'fisico','12', NULL, '2019-04-11', 'assets/img/libros/hermosas-criaturas.jpg',null),
        (NULL, '3', 'El secreto de Xein','Laura Gallego', 'Resume', '17', 'ebook','12', NULL, '2019-04-11', 'assets/img/libros/la-ladrona-de-libros.jpg',null),
        (NULL, '3', 'El secreto de Xein','Laura Gallego', 'Resume', '17', 'fisico','12', NULL, '2019-04-11', 'assets/img/libros/los-juegos-del-hambre.jpg',null),
        (NULL, '3', 'El secreto de Xein','Laura Gallego', 'Resume', '17', 'ebook','12', NULL, '2019-04-11', 'assets/img/libros/sinsajo.jpg',null),
        (NULL, '3', 'El secreto de Xein','Laura Gallego', 'Resume', '17', 'fisico','12', NULL, '2019-04-11', 'assets/img/libros/ciudades-de-papel.jpg',null),
        (NULL, '3', 'El secreto de Xein','Laura Gallego', 'Resume', '17', 'ebook','12', NULL, '2019-04-11', 'assets/img/libros/tambores-de-otoño.jpg',null),

        /*Romantica*/
        (NULL, '2', '50 sombras de grey', 'E. L. James','Cuando la estudiante de literatura Anastasia Steele recibe el encargo de entrevistar al exitoso y joven empresario Christian Grey, queda impresionada al encontrarse ante un hombre atractivo, seductor y también muy intimidante. La inexperta e inocente Ana intenta olvidarle, pero pronto comprende cuánto le desea.
        Grey está atormentado por sus propios demonios y le consume la necesidad de controlarlo todo, pero a su vez se ve incapaz de resistirse a la serena belleza de Ana, a su inteligencia y a su espíritu independiente. Debe admitir que la desea, pero bajo ciertas condiciones.
        Cuando la pareja por fin inicia una apasionada relación, las peculiares prácticas eróticas de Grey desconciertan a Ana, al tiempo que ella descubre los límites de sus propios y más oscuros deseos...', '20', 'fisico','12', NULL, '2019-04-11', 'assets/img/libros/grey.jpg',null),
        (NULL, '2', 'El secreto de Xein','Laura Gallego', 'Resume', '17', 'ebook','12', NULL, '2019-04-11', 'assets/img/libros/dejame-ser-tu-chico-malo.jpg',null),
        (NULL, '2', 'El secreto de Xein','Laura Gallego', 'Resume', '17', 'fisico','12', NULL, '2019-04-11', 'assets/img/libros/el-dia-que-el-cielo-se-caiga.jpg',null),
        (NULL, '2', 'El secreto de Xein','Laura Gallego', 'Resume', '17', 'ebook','12', NULL, '2019-04-11', 'assets/img/libros/en-los-zapatos-de-valeria.jpg',null),
        (NULL, '2', 'El secreto de Xein','Laura Gallego', 'Resume', '17', 'fisico','12', NULL, '2019-04-11', 'assets/img/libros/la-ultima-carta-de-amor.jpg',null),
        (NULL, '2', 'El secreto de Xein','Laura Gallego', 'Resume', '17', 'ebook','12', NULL, '2019-04-11', 'assets/img/libros/todo-lo-que-somos-juntos.jpg',null),
        (NULL, '2', 'El secreto de Xein','Laura Gallego', 'Resume', '17', 'fisico','12', NULL, '2019-04-11', 'assets/img/libros/valeria-al-desnudo.jpg',null),
        (NULL, '2', 'El secreto de Xein','Laura Gallego', 'Resume', '17', 'ebook','12', NULL, '2019-04-11', 'assets/img/libros/valeria-en-blanco-y-negro.jpg',null),
        (NULL, '2', 'El secreto de Xein','Laura Gallego', 'Resume', '17', 'fisico','12', NULL, '2019-04-11', 'assets/img/libros/valeria-en-el-espejo.jpg',null),
        (NULL, '2', 'El secreto de Xein','Laura Gallego', 'Resume', '17', 'ebook','12', NULL, '2019-04-11', 'assets/img/libros/yo-antes-de-ti.jpg',null);

